name: brew-install-test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install:
    runs-on: macos-15
    steps:
      - name: Install tap & eth
        run: |
          brew tap ayushm2003/ethup
          brew install eth
          eth --help
